import type { IconComponent } from "reicon-react";
import {
  Code,
  CodeCircle,
  CodeSquare,
  BrowserTerminal,
  Command,
  CommandSquare,
  Cpu,
  Database,
  Server,
  Bug,
  Hierarchy,
  Data,
  Data2,
  Fingerprint,
  Microchip,
  Cloud,
  CloudConnection,
  CloudLightning,
  Computing,
  Programming,
  Router,
  Wifi,
  Security,
  Layers,
  Layers2,
  Box,
  Box2,
  Component,
  Palette,
  Brush,
  Pen,
  Pen2,
  PenTool,
  Shapes,
  Ruler,
  Ruler2,
  Sparkle,
  Sparkles,
  Wand,
  Frame,
  Layout,
  Grid,
  Grid2,
  Grid3,
  Grid4,
  Element,
  Element2,
  Element3,
  Slider,
  SliderHorizontal,
  SliderVertical,
  ColorSwatch,
  Crop,
  Scissors,
  Maximize,
  Minimize,
  Chart,
  Chart2,
  ChartBar,
  ChartPie,
  ChartSquare,
  Diagram,
  Presentation,
  TrendUp,
  TrendDown,
  Activity,
  Target,
  Briefcase,
  Briefcase2,
  Wallet,
  Wallet2,
  CreditCard,
  Card,
  Coins,
  Dollar,
  DollarCircle,
  DollarSquare,
  Euro,
  Receipt,
  Bill,
  Invoice,
  Calculator,
  Shop,
  ShoppingBag,
  ShoppingCart,
  Store,
  Building,
  Bank,
  Crown,
  Crown2,
  Cup,
  Trophy,
  Medal,
  Award,
  Shield,
  ShieldCheck,
  ShieldCross,
  ShieldMinus,
  ShieldPlus,
  ShieldSecurity,
  ShieldSlash,
  ShieldTick,
  Lock,
  LockCircle,
  LockSlash,
  Unlock,
  Key,
  KeySquare,
  Password,
  PasswordCheck,
  Scan,
  ScanBarcode,
  SecurityCard,
  SecuritySafe,
  SecurityTime,
  SecurityUser,
  FingerScan,
  Eye,
  EyeSlash,
  EyeOff,
  SafeHome,
  Verified,
  Task,
  TaskSquare,
  Checklist,
  Clipboard,
  ClipboardClose,
  ClipboardExport,
  ClipboardImport,
  ClipboardText,
  ClipboardTick,
  Document as ReiconDocument,
  DocumentCode,
  DocumentCopy,
  DocumentDownload,
  DocumentFavorite,
  DocumentFilter,
  DocumentForward,
  DocumentNormal,
  DocumentSketch,
  DocumentText,
  DocumentUpload,
  Note,
  Note2,
  NoteAdd,
  NoteFavorite,
  NoteRemove,
  NoteSquare,
  NoteText,
  Folder,
  Folder2,
  FolderAdd,
  FolderCheck,
  FolderCloud,
  FolderConnection,
  FolderCross,
  FolderFavorite,
  FolderMinus,
  FolderOpen,
  Archive,
  ArchiveBox,
  ArchiveBook,
  Tag,
  Tag2,
  TagCross,
  TagRight,
  TagUser,
  Hashtag,
  HashtagDown,
  HashtagUp,
  Bookmark,
  Bookmark2,
  Book,
  BookSaved,
  BookSquare,
  Message,
  Message2,
  MessageCircle,
  MessageDots,
  MessageEdit,
  MessageFavorite,
  MessageMinus,
  MessagePlus,
  MessageQuestion,
  MessageSearch,
  MessageSquare,
  MessageText,
  Messages,
  Messages2,
  Sms,
  SmsEdit,
  SmsNotification,
  SmsSearch,
  SmsTracking,
  Inbox,
  InboxIn,
  InboxOut,
  Send,
  Send2,
  Share,
  ShareCircle,
  Phone,
  Call,
  Notification,
  NotificationBing,
  NotificationCircle,
  NotificationFavorite,
  NotificationStatus,
  Bell,
  BellRing,
  Mobile,
  MobileProgramming,
  Devices,
  Monitor,
  MonitorRecorder,
  Laptop,
  Computer,
  Tablet,
  Mouse,
  Keyboard,
  Printer,
  HardDrive,
  Usb,
  Headphone,
  Headphones,
  Speaker,
  Microphone,
  Camera,
  Video,
  VideoCircle,
  VideoPlay,
  VideoSquare,
  Compass,
  CompassSquare,
  Map as ReiconMap,
  Location,
  LocationCross,
  LocationMinus,
  LocationSlash,
  LocationTick,
  Gps,
  Route,
  Flag,
  Flag2,
  Anchor,
  Rocket,
  Flame,
  Fire,
  Bolt,
  Flash,
  FlashCircle,
  FlashSlash,
  Star,
  StarSlash,
  Heart,
  HeartCircle,
  HeartRemove,
  HeartSearch,
  HeartSlash,
  HeartTick,
  Like,
  LikeShapes,
  LikeTag,
  Dislike,
  Search,
  SearchFavorite,
  SearchNormal,
  SearchStatus,
  SearchZoomIn,
  SearchZoomOut,
  Filter,
  FilterAdd,
  FilterEdit,
  FilterRemove,
  FilterSearch,
  FilterSquare,
  FilterTick,
  Sort,
  Refresh,
  Refresh2,
  RefreshCircle,
  RefreshLeftSquare,
  RefreshRightSquare,
  RefreshSquare,
  Repeat,
  RepeatCircle,
  Link,
  Link2,
  LinkCircle,
  LinkSquare,
  Paperclip,
  Paperclip2,
  Globe,
  Clock,
  Clock2,
  ClockCircle,
  ClockSquare,
  Watch,
  Timer,
  Stopwatch,
  Hourglass,
  Calendar,
  Calendar2,
  CalendarAdd,
  CalendarCircle,
  CalendarEdit,
  CalendarMinus,
  CalendarRemove,
  CalendarSearch,
  CalendarTick,
  User,
  UserAdd,
  UserCheck,
  UserCircle,
  UserEdit,
  UserMinus,
  UserOctagon,
  UserRemove,
  UserSearch,
  UserSquare,
  UserTag,
  UserTick,
  Users,
  People,
  Profile,
  ProfileAdd,
  ProfileCircle,
  ProfileDelete,
  ProfileRemove,
  ProfileTick,
  Group
} from "reicon-react";

export type IconCategory =
  | "all"
  | "dev"
  | "design"
  | "business"
  | "security"
  | "workflow"
  | "communication"
  | "system";

export interface RegistryIcon {
  id: string;
  name: string;
  category: "dev" | "design" | "business" | "security" | "workflow" | "communication" | "system";
  component: IconComponent;
}

export const ICON_CATEGORIES: { id: IconCategory; label: string }[] = [
  { id: "all", label: "Tutte (331)" },
  { id: "dev", label: "Sviluppo (23)" },
  { id: "design", label: "Design (33)" },
  { id: "business", label: "Business (38)" },
  { id: "security", label: "Sicurezza (28)" },
  { id: "workflow", label: "Attività (53)" },
  { id: "communication", label: "Comunicazione (35)" },
  { id: "system", label: "Sistema (121)" },
];

export const CURATED_REICONS: RegistryIcon[] = [
  { id: "code", name: "Code", category: "dev", component: Code },
  { id: "codecircle", name: "Code Circle", category: "dev", component: CodeCircle },
  { id: "codesquare", name: "Code Square", category: "dev", component: CodeSquare },
  { id: "browserterminal", name: "Browser Terminal", category: "dev", component: BrowserTerminal },
  { id: "command", name: "Command", category: "dev", component: Command },
  { id: "commandsquare", name: "Command Square", category: "dev", component: CommandSquare },
  { id: "cpu", name: "Cpu", category: "dev", component: Cpu },
  { id: "database", name: "Database", category: "dev", component: Database },
  { id: "server", name: "Server", category: "dev", component: Server },
  { id: "bug", name: "Bug", category: "dev", component: Bug },
  { id: "hierarchy", name: "Hierarchy", category: "dev", component: Hierarchy },
  { id: "data", name: "Data", category: "dev", component: Data },
  { id: "data2", name: "Data 2", category: "dev", component: Data2 },
  { id: "fingerprint", name: "Fingerprint", category: "dev", component: Fingerprint },
  { id: "microchip", name: "Microchip", category: "dev", component: Microchip },
  { id: "cloud", name: "Cloud", category: "dev", component: Cloud },
  { id: "cloudconnection", name: "Cloud Connection", category: "dev", component: CloudConnection },
  { id: "cloudlightning", name: "Cloud Lightning", category: "dev", component: CloudLightning },
  { id: "computing", name: "Computing", category: "dev", component: Computing },
  { id: "programming", name: "Programming", category: "dev", component: Programming },
  { id: "router", name: "Router", category: "dev", component: Router },
  { id: "wifi", name: "Wifi", category: "dev", component: Wifi },
  { id: "security", name: "Security", category: "dev", component: Security },
  { id: "layers", name: "Layers", category: "design", component: Layers },
  { id: "layers2", name: "Layers 2", category: "design", component: Layers2 },
  { id: "box", name: "Box", category: "design", component: Box },
  { id: "box2", name: "Box 2", category: "design", component: Box2 },
  { id: "component", name: "Component", category: "design", component: Component },
  { id: "palette", name: "Palette", category: "design", component: Palette },
  { id: "brush", name: "Brush", category: "design", component: Brush },
  { id: "pen", name: "Pen", category: "design", component: Pen },
  { id: "pen2", name: "Pen 2", category: "design", component: Pen2 },
  { id: "pentool", name: "Pen Tool", category: "design", component: PenTool },
  { id: "shapes", name: "Shapes", category: "design", component: Shapes },
  { id: "ruler", name: "Ruler", category: "design", component: Ruler },
  { id: "ruler2", name: "Ruler 2", category: "design", component: Ruler2 },
  { id: "sparkle", name: "Sparkle", category: "design", component: Sparkle },
  { id: "sparkles", name: "Sparkles", category: "design", component: Sparkles },
  { id: "wand", name: "Wand", category: "design", component: Wand },
  { id: "frame", name: "Frame", category: "design", component: Frame },
  { id: "layout", name: "Layout", category: "design", component: Layout },
  { id: "grid", name: "Grid", category: "design", component: Grid },
  { id: "grid2", name: "Grid 2", category: "design", component: Grid2 },
  { id: "grid3", name: "Grid 3", category: "design", component: Grid3 },
  { id: "grid4", name: "Grid 4", category: "design", component: Grid4 },
  { id: "element", name: "Element", category: "design", component: Element },
  { id: "element2", name: "Element 2", category: "design", component: Element2 },
  { id: "element3", name: "Element 3", category: "design", component: Element3 },
  { id: "slider", name: "Slider", category: "design", component: Slider },
  { id: "sliderhorizontal", name: "Slider Horizontal", category: "design", component: SliderHorizontal },
  { id: "slidervertical", name: "Slider Vertical", category: "design", component: SliderVertical },
  { id: "colorswatch", name: "Color Swatch", category: "design", component: ColorSwatch },
  { id: "crop", name: "Crop", category: "design", component: Crop },
  { id: "scissors", name: "Scissors", category: "design", component: Scissors },
  { id: "maximize", name: "Maximize", category: "design", component: Maximize },
  { id: "minimize", name: "Minimize", category: "design", component: Minimize },
  { id: "chart", name: "Chart", category: "business", component: Chart },
  { id: "chart2", name: "Chart 2", category: "business", component: Chart2 },
  { id: "chartbar", name: "Chart Bar", category: "business", component: ChartBar },
  { id: "chartpie", name: "Chart Pie", category: "business", component: ChartPie },
  { id: "chartsquare", name: "Chart Square", category: "business", component: ChartSquare },
  { id: "diagram", name: "Diagram", category: "business", component: Diagram },
  { id: "presentation", name: "Presentation", category: "business", component: Presentation },
  { id: "trendup", name: "Trend Up", category: "business", component: TrendUp },
  { id: "trenddown", name: "Trend Down", category: "business", component: TrendDown },
  { id: "activity", name: "Activity", category: "business", component: Activity },
  { id: "target", name: "Target", category: "business", component: Target },
  { id: "briefcase", name: "Briefcase", category: "business", component: Briefcase },
  { id: "briefcase2", name: "Briefcase 2", category: "business", component: Briefcase2 },
  { id: "wallet", name: "Wallet", category: "business", component: Wallet },
  { id: "wallet2", name: "Wallet 2", category: "business", component: Wallet2 },
  { id: "creditcard", name: "Credit Card", category: "business", component: CreditCard },
  { id: "card", name: "Card", category: "business", component: Card },
  { id: "coins", name: "Coins", category: "business", component: Coins },
  { id: "dollar", name: "Dollar", category: "business", component: Dollar },
  { id: "dollarcircle", name: "Dollar Circle", category: "business", component: DollarCircle },
  { id: "dollarsquare", name: "Dollar Square", category: "business", component: DollarSquare },
  { id: "euro", name: "Euro", category: "business", component: Euro },
  { id: "receipt", name: "Receipt", category: "business", component: Receipt },
  { id: "bill", name: "Bill", category: "business", component: Bill },
  { id: "invoice", name: "Invoice", category: "business", component: Invoice },
  { id: "calculator", name: "Calculator", category: "business", component: Calculator },
  { id: "shop", name: "Shop", category: "business", component: Shop },
  { id: "shoppingbag", name: "Shopping Bag", category: "business", component: ShoppingBag },
  { id: "shoppingcart", name: "Shopping Cart", category: "business", component: ShoppingCart },
  { id: "store", name: "Store", category: "business", component: Store },
  { id: "building", name: "Building", category: "business", component: Building },
  { id: "bank", name: "Bank", category: "business", component: Bank },
  { id: "crown", name: "Crown", category: "business", component: Crown },
  { id: "crown2", name: "Crown 2", category: "business", component: Crown2 },
  { id: "cup", name: "Cup", category: "business", component: Cup },
  { id: "trophy", name: "Trophy", category: "business", component: Trophy },
  { id: "medal", name: "Medal", category: "business", component: Medal },
  { id: "award", name: "Award", category: "business", component: Award },
  { id: "shield", name: "Shield", category: "security", component: Shield },
  { id: "shieldcheck", name: "Shield Check", category: "security", component: ShieldCheck },
  { id: "shieldcross", name: "Shield Cross", category: "security", component: ShieldCross },
  { id: "shieldminus", name: "Shield Minus", category: "security", component: ShieldMinus },
  { id: "shieldplus", name: "Shield Plus", category: "security", component: ShieldPlus },
  { id: "shieldsecurity", name: "Shield Security", category: "security", component: ShieldSecurity },
  { id: "shieldslash", name: "Shield Slash", category: "security", component: ShieldSlash },
  { id: "shieldtick", name: "Shield Tick", category: "security", component: ShieldTick },
  { id: "lock", name: "Lock", category: "security", component: Lock },
  { id: "lockcircle", name: "Lock Circle", category: "security", component: LockCircle },
  { id: "lockslash", name: "Lock Slash", category: "security", component: LockSlash },
  { id: "unlock", name: "Unlock", category: "security", component: Unlock },
  { id: "key", name: "Key", category: "security", component: Key },
  { id: "keysquare", name: "Key Square", category: "security", component: KeySquare },
  { id: "password", name: "Password", category: "security", component: Password },
  { id: "passwordcheck", name: "Password Check", category: "security", component: PasswordCheck },
  { id: "scan", name: "Scan", category: "security", component: Scan },
  { id: "scanbarcode", name: "Scan Barcode", category: "security", component: ScanBarcode },
  { id: "securitycard", name: "Security Card", category: "security", component: SecurityCard },
  { id: "securitysafe", name: "Security Safe", category: "security", component: SecuritySafe },
  { id: "securitytime", name: "Security Time", category: "security", component: SecurityTime },
  { id: "securityuser", name: "Security User", category: "security", component: SecurityUser },
  { id: "fingerscan", name: "Finger Scan", category: "security", component: FingerScan },
  { id: "eye", name: "Eye", category: "security", component: Eye },
  { id: "eyeslash", name: "Eye Slash", category: "security", component: EyeSlash },
  { id: "eyeoff", name: "Eye Off", category: "security", component: EyeOff },
  { id: "safehome", name: "Safe Home", category: "security", component: SafeHome },
  { id: "verified", name: "Verified", category: "security", component: Verified },
  { id: "task", name: "Task", category: "workflow", component: Task },
  { id: "tasksquare", name: "Task Square", category: "workflow", component: TaskSquare },
  { id: "checklist", name: "Checklist", category: "workflow", component: Checklist },
  { id: "clipboard", name: "Clipboard", category: "workflow", component: Clipboard },
  { id: "clipboardclose", name: "Clipboard Close", category: "workflow", component: ClipboardClose },
  { id: "clipboardexport", name: "Clipboard Export", category: "workflow", component: ClipboardExport },
  { id: "clipboardimport", name: "Clipboard Import", category: "workflow", component: ClipboardImport },
  { id: "clipboardtext", name: "Clipboard Text", category: "workflow", component: ClipboardText },
  { id: "clipboardtick", name: "Clipboard Tick", category: "workflow", component: ClipboardTick },
  { id: "document", name: "Document", category: "workflow", component: ReiconDocument },
  { id: "documentcode", name: "Document Code", category: "workflow", component: DocumentCode },
  { id: "documentcopy", name: "Document Copy", category: "workflow", component: DocumentCopy },
  { id: "documentdownload", name: "Document Download", category: "workflow", component: DocumentDownload },
  { id: "documentfavorite", name: "Document Favorite", category: "workflow", component: DocumentFavorite },
  { id: "documentfilter", name: "Document Filter", category: "workflow", component: DocumentFilter },
  { id: "documentforward", name: "Document Forward", category: "workflow", component: DocumentForward },
  { id: "documentnormal", name: "Document Normal", category: "workflow", component: DocumentNormal },
  { id: "documentsketch", name: "Document Sketch", category: "workflow", component: DocumentSketch },
  { id: "documenttext", name: "Document Text", category: "workflow", component: DocumentText },
  { id: "documentupload", name: "Document Upload", category: "workflow", component: DocumentUpload },
  { id: "note", name: "Note", category: "workflow", component: Note },
  { id: "note2", name: "Note 2", category: "workflow", component: Note2 },
  { id: "noteadd", name: "Note Add", category: "workflow", component: NoteAdd },
  { id: "notefavorite", name: "Note Favorite", category: "workflow", component: NoteFavorite },
  { id: "noteremove", name: "Note Remove", category: "workflow", component: NoteRemove },
  { id: "notesquare", name: "Note Square", category: "workflow", component: NoteSquare },
  { id: "notetext", name: "Note Text", category: "workflow", component: NoteText },
  { id: "folder", name: "Folder", category: "workflow", component: Folder },
  { id: "folder2", name: "Folder 2", category: "workflow", component: Folder2 },
  { id: "folderadd", name: "Folder Add", category: "workflow", component: FolderAdd },
  { id: "foldercheck", name: "Folder Check", category: "workflow", component: FolderCheck },
  { id: "foldercloud", name: "Folder Cloud", category: "workflow", component: FolderCloud },
  { id: "folderconnection", name: "Folder Connection", category: "workflow", component: FolderConnection },
  { id: "foldercross", name: "Folder Cross", category: "workflow", component: FolderCross },
  { id: "folderfavorite", name: "Folder Favorite", category: "workflow", component: FolderFavorite },
  { id: "folderminus", name: "Folder Minus", category: "workflow", component: FolderMinus },
  { id: "folderopen", name: "Folder Open", category: "workflow", component: FolderOpen },
  { id: "archive", name: "Archive", category: "workflow", component: Archive },
  { id: "archivebox", name: "Archive Box", category: "workflow", component: ArchiveBox },
  { id: "archivebook", name: "Archive Book", category: "workflow", component: ArchiveBook },
  { id: "tag", name: "Tag", category: "workflow", component: Tag },
  { id: "tag2", name: "Tag 2", category: "workflow", component: Tag2 },
  { id: "tagcross", name: "Tag Cross", category: "workflow", component: TagCross },
  { id: "tagright", name: "Tag Right", category: "workflow", component: TagRight },
  { id: "taguser", name: "Tag User", category: "workflow", component: TagUser },
  { id: "hashtag", name: "Hashtag", category: "workflow", component: Hashtag },
  { id: "hashtagdown", name: "Hashtag Down", category: "workflow", component: HashtagDown },
  { id: "hashtagup", name: "Hashtag Up", category: "workflow", component: HashtagUp },
  { id: "bookmark", name: "Bookmark", category: "workflow", component: Bookmark },
  { id: "bookmark2", name: "Bookmark 2", category: "workflow", component: Bookmark2 },
  { id: "book", name: "Book", category: "workflow", component: Book },
  { id: "booksaved", name: "Book Saved", category: "workflow", component: BookSaved },
  { id: "booksquare", name: "Book Square", category: "workflow", component: BookSquare },
  { id: "message", name: "Message", category: "communication", component: Message },
  { id: "message2", name: "Message 2", category: "communication", component: Message2 },
  { id: "messagecircle", name: "Message Circle", category: "communication", component: MessageCircle },
  { id: "messagedots", name: "Message Dots", category: "communication", component: MessageDots },
  { id: "messageedit", name: "Message Edit", category: "communication", component: MessageEdit },
  { id: "messagefavorite", name: "Message Favorite", category: "communication", component: MessageFavorite },
  { id: "messageminus", name: "Message Minus", category: "communication", component: MessageMinus },
  { id: "messageplus", name: "Message Plus", category: "communication", component: MessagePlus },
  { id: "messagequestion", name: "Message Question", category: "communication", component: MessageQuestion },
  { id: "messagesearch", name: "Message Search", category: "communication", component: MessageSearch },
  { id: "messagesquare", name: "Message Square", category: "communication", component: MessageSquare },
  { id: "messagetext", name: "Message Text", category: "communication", component: MessageText },
  { id: "messages", name: "Messages", category: "communication", component: Messages },
  { id: "messages2", name: "Messages 2", category: "communication", component: Messages2 },
  { id: "sms", name: "Sms", category: "communication", component: Sms },
  { id: "smsedit", name: "Sms Edit", category: "communication", component: SmsEdit },
  { id: "smsnotification", name: "Sms Notification", category: "communication", component: SmsNotification },
  { id: "smssearch", name: "Sms Search", category: "communication", component: SmsSearch },
  { id: "smstracking", name: "Sms Tracking", category: "communication", component: SmsTracking },
  { id: "inbox", name: "Inbox", category: "communication", component: Inbox },
  { id: "inboxin", name: "Inbox In", category: "communication", component: InboxIn },
  { id: "inboxout", name: "Inbox Out", category: "communication", component: InboxOut },
  { id: "send", name: "Send", category: "communication", component: Send },
  { id: "send2", name: "Send 2", category: "communication", component: Send2 },
  { id: "share", name: "Share", category: "communication", component: Share },
  { id: "sharecircle", name: "Share Circle", category: "communication", component: ShareCircle },
  { id: "phone", name: "Phone", category: "communication", component: Phone },
  { id: "call", name: "Call", category: "communication", component: Call },
  { id: "notification", name: "Notification", category: "communication", component: Notification },
  { id: "notificationbing", name: "Notification Bing", category: "communication", component: NotificationBing },
  { id: "notificationcircle", name: "Notification Circle", category: "communication", component: NotificationCircle },
  { id: "notificationfavorite", name: "Notification Favorite", category: "communication", component: NotificationFavorite },
  { id: "notificationstatus", name: "Notification Status", category: "communication", component: NotificationStatus },
  { id: "bell", name: "Bell", category: "communication", component: Bell },
  { id: "bellring", name: "Bell Ring", category: "communication", component: BellRing },
  { id: "mobile", name: "Mobile", category: "system", component: Mobile },
  { id: "mobileprogramming", name: "Mobile Programming", category: "system", component: MobileProgramming },
  { id: "devices", name: "Devices", category: "system", component: Devices },
  { id: "monitor", name: "Monitor", category: "system", component: Monitor },
  { id: "monitorrecorder", name: "Monitor Recorder", category: "system", component: MonitorRecorder },
  { id: "laptop", name: "Laptop", category: "system", component: Laptop },
  { id: "computer", name: "Computer", category: "system", component: Computer },
  { id: "tablet", name: "Tablet", category: "system", component: Tablet },
  { id: "mouse", name: "Mouse", category: "system", component: Mouse },
  { id: "keyboard", name: "Keyboard", category: "system", component: Keyboard },
  { id: "printer", name: "Printer", category: "system", component: Printer },
  { id: "harddrive", name: "Hard Drive", category: "system", component: HardDrive },
  { id: "usb", name: "Usb", category: "system", component: Usb },
  { id: "headphone", name: "Headphone", category: "system", component: Headphone },
  { id: "headphones", name: "Headphones", category: "system", component: Headphones },
  { id: "speaker", name: "Speaker", category: "system", component: Speaker },
  { id: "microphone", name: "Microphone", category: "system", component: Microphone },
  { id: "camera", name: "Camera", category: "system", component: Camera },
  { id: "video", name: "Video", category: "system", component: Video },
  { id: "videocircle", name: "Video Circle", category: "system", component: VideoCircle },
  { id: "videoplay", name: "Video Play", category: "system", component: VideoPlay },
  { id: "videosquare", name: "Video Square", category: "system", component: VideoSquare },
  { id: "compass", name: "Compass", category: "system", component: Compass },
  { id: "compasssquare", name: "Compass Square", category: "system", component: CompassSquare },
  { id: "map", name: "Map", category: "system", component: ReiconMap },
  { id: "location", name: "Location", category: "system", component: Location },
  { id: "locationcross", name: "Location Cross", category: "system", component: LocationCross },
  { id: "locationminus", name: "Location Minus", category: "system", component: LocationMinus },
  { id: "locationslash", name: "Location Slash", category: "system", component: LocationSlash },
  { id: "locationtick", name: "Location Tick", category: "system", component: LocationTick },
  { id: "gps", name: "Gps", category: "system", component: Gps },
  { id: "route", name: "Route", category: "system", component: Route },
  { id: "flag", name: "Flag", category: "system", component: Flag },
  { id: "flag2", name: "Flag 2", category: "system", component: Flag2 },
  { id: "anchor", name: "Anchor", category: "system", component: Anchor },
  { id: "rocket", name: "Rocket", category: "system", component: Rocket },
  { id: "flame", name: "Flame", category: "system", component: Flame },
  { id: "fire", name: "Fire", category: "system", component: Fire },
  { id: "bolt", name: "Bolt", category: "system", component: Bolt },
  { id: "flash", name: "Flash", category: "system", component: Flash },
  { id: "flashcircle", name: "Flash Circle", category: "system", component: FlashCircle },
  { id: "flashslash", name: "Flash Slash", category: "system", component: FlashSlash },
  { id: "star", name: "Star", category: "system", component: Star },
  { id: "starslash", name: "Star Slash", category: "system", component: StarSlash },
  { id: "heart", name: "Heart", category: "system", component: Heart },
  { id: "heartcircle", name: "Heart Circle", category: "system", component: HeartCircle },
  { id: "heartremove", name: "Heart Remove", category: "system", component: HeartRemove },
  { id: "heartsearch", name: "Heart Search", category: "system", component: HeartSearch },
  { id: "heartslash", name: "Heart Slash", category: "system", component: HeartSlash },
  { id: "hearttick", name: "Heart Tick", category: "system", component: HeartTick },
  { id: "like", name: "Like", category: "system", component: Like },
  { id: "likeshapes", name: "Like Shapes", category: "system", component: LikeShapes },
  { id: "liketag", name: "Like Tag", category: "system", component: LikeTag },
  { id: "dislike", name: "Dislike", category: "system", component: Dislike },
  { id: "search", name: "Search", category: "system", component: Search },
  { id: "searchfavorite", name: "Search Favorite", category: "system", component: SearchFavorite },
  { id: "searchnormal", name: "Search Normal", category: "system", component: SearchNormal },
  { id: "searchstatus", name: "Search Status", category: "system", component: SearchStatus },
  { id: "searchzoomin", name: "Search Zoom In", category: "system", component: SearchZoomIn },
  { id: "searchzoomout", name: "Search Zoom Out", category: "system", component: SearchZoomOut },
  { id: "filter", name: "Filter", category: "system", component: Filter },
  { id: "filteradd", name: "Filter Add", category: "system", component: FilterAdd },
  { id: "filteredit", name: "Filter Edit", category: "system", component: FilterEdit },
  { id: "filterremove", name: "Filter Remove", category: "system", component: FilterRemove },
  { id: "filtersearch", name: "Filter Search", category: "system", component: FilterSearch },
  { id: "filtersquare", name: "Filter Square", category: "system", component: FilterSquare },
  { id: "filtertick", name: "Filter Tick", category: "system", component: FilterTick },
  { id: "sort", name: "Sort", category: "system", component: Sort },
  { id: "refresh", name: "Refresh", category: "system", component: Refresh },
  { id: "refresh2", name: "Refresh 2", category: "system", component: Refresh2 },
  { id: "refreshcircle", name: "Refresh Circle", category: "system", component: RefreshCircle },
  { id: "refreshleftsquare", name: "Refresh Left Square", category: "system", component: RefreshLeftSquare },
  { id: "refreshrightsquare", name: "Refresh Right Square", category: "system", component: RefreshRightSquare },
  { id: "refreshsquare", name: "Refresh Square", category: "system", component: RefreshSquare },
  { id: "repeat", name: "Repeat", category: "system", component: Repeat },
  { id: "repeatcircle", name: "Repeat Circle", category: "system", component: RepeatCircle },
  { id: "link", name: "Link", category: "system", component: Link },
  { id: "link2", name: "Link 2", category: "system", component: Link2 },
  { id: "linkcircle", name: "Link Circle", category: "system", component: LinkCircle },
  { id: "linksquare", name: "Link Square", category: "system", component: LinkSquare },
  { id: "paperclip", name: "Paperclip", category: "system", component: Paperclip },
  { id: "paperclip2", name: "Paperclip 2", category: "system", component: Paperclip2 },
  { id: "globe", name: "Globe", category: "system", component: Globe },
  { id: "clock", name: "Clock", category: "system", component: Clock },
  { id: "clock2", name: "Clock 2", category: "system", component: Clock2 },
  { id: "clockcircle", name: "Clock Circle", category: "system", component: ClockCircle },
  { id: "clocksquare", name: "Clock Square", category: "system", component: ClockSquare },
  { id: "watch", name: "Watch", category: "system", component: Watch },
  { id: "timer", name: "Timer", category: "system", component: Timer },
  { id: "stopwatch", name: "Stopwatch", category: "system", component: Stopwatch },
  { id: "hourglass", name: "Hourglass", category: "system", component: Hourglass },
  { id: "calendar", name: "Calendar", category: "system", component: Calendar },
  { id: "calendar2", name: "Calendar 2", category: "system", component: Calendar2 },
  { id: "calendaradd", name: "Calendar Add", category: "system", component: CalendarAdd },
  { id: "calendarcircle", name: "Calendar Circle", category: "system", component: CalendarCircle },
  { id: "calendaredit", name: "Calendar Edit", category: "system", component: CalendarEdit },
  { id: "calendarminus", name: "Calendar Minus", category: "system", component: CalendarMinus },
  { id: "calendarremove", name: "Calendar Remove", category: "system", component: CalendarRemove },
  { id: "calendarsearch", name: "Calendar Search", category: "system", component: CalendarSearch },
  { id: "calendartick", name: "Calendar Tick", category: "system", component: CalendarTick },
  { id: "user", name: "User", category: "system", component: User },
  { id: "useradd", name: "User Add", category: "system", component: UserAdd },
  { id: "usercheck", name: "User Check", category: "system", component: UserCheck },
  { id: "usercircle", name: "User Circle", category: "system", component: UserCircle },
  { id: "useredit", name: "User Edit", category: "system", component: UserEdit },
  { id: "userminus", name: "User Minus", category: "system", component: UserMinus },
  { id: "useroctagon", name: "User Octagon", category: "system", component: UserOctagon },
  { id: "userremove", name: "User Remove", category: "system", component: UserRemove },
  { id: "usersearch", name: "User Search", category: "system", component: UserSearch },
  { id: "usersquare", name: "User Square", category: "system", component: UserSquare },
  { id: "usertag", name: "User Tag", category: "system", component: UserTag },
  { id: "usertick", name: "User Tick", category: "system", component: UserTick },
  { id: "users", name: "Users", category: "system", component: Users },
  { id: "people", name: "People", category: "system", component: People },
  { id: "profile", name: "Profile", category: "system", component: Profile },
  { id: "profileadd", name: "Profile Add", category: "system", component: ProfileAdd },
  { id: "profilecircle", name: "Profile Circle", category: "system", component: ProfileCircle },
  { id: "profiledelete", name: "Profile Delete", category: "system", component: ProfileDelete },
  { id: "profileremove", name: "Profile Remove", category: "system", component: ProfileRemove },
  { id: "profiletick", name: "Profile Tick", category: "system", component: ProfileTick },
  { id: "group", name: "Group", category: "system", component: Group }
];

const REICON_REGISTRY_MAP: Record<string, IconComponent> = {};

for (const item of CURATED_REICONS) {
  REICON_REGISTRY_MAP[item.id] = item.component;
  REICON_REGISTRY_MAP[item.name.toLowerCase().replace(/\s+/g, "")] = item.component;
}

const ICON_ALIASES: Record<string, string> = {
  db: "database",
  database: "database",
  zap: "bolt",
  bolt: "bolt",
  lightning: "bolt",
  cube: "box",
  box: "box",
  layer: "layers",
  layers: "layers",
  security: "shield",
  shield: "shield",
  terminal: "browserterminal",
  cli: "browserterminal",
  console: "command",
  web: "globe",
  globe: "globe",
  ai: "sparkles",
  sparkles: "sparkles",
  chip: "cpu",
  cpu: "cpu",
  fire: "flame",
  flame: "flame",
  activity: "activity",
  pulse: "activity",
  compass: "compass",
  code: "code",
  layout: "layout",
  server: "server",
  cloud: "cloud",
  git: "gitbranch",
  "git-branch": "gitbranch",
  branch: "gitbranch",
  workflow: "hierarchy",
  hierarchy: "hierarchy",
  lock: "lock",
  rocket: "rocket",
  launch: "rocket",
  key: "key",
  search: "search",
  star: "star",
  folder: "folder",
  check: "checklist",
  file: "document",
  storage: "harddrive",
  drive: "harddrive",
  bookmark: "bookmark",
  tag: "tag",
  hashtag: "hashtag",
  chart: "chartbar",
  route: "route",
  diagram: "diagram",
};

export function getReicon(nameOrId?: string | null): IconComponent | null {
  if (!nameOrId) return null;
  const norm = nameOrId.toLowerCase().trim().replace(/[-_\s]+/g, "");
  const aliasTarget = ICON_ALIASES[norm] || ICON_ALIASES[nameOrId.toLowerCase().trim()];
  if (aliasTarget && REICON_REGISTRY_MAP[aliasTarget]) {
    return REICON_REGISTRY_MAP[aliasTarget];
  }
  if (REICON_REGISTRY_MAP[norm]) {
    return REICON_REGISTRY_MAP[norm];
  }
  return null;
}

export function searchReicons(query: string, category: IconCategory = "all"): RegistryIcon[] {
  const q = query.toLowerCase().trim();
  return CURATED_REICONS.filter((item) => {
    const matchesCategory = category === "all" || item.category === category;
    if (!matchesCategory) return false;
    if (!q) return true;
    return item.id.includes(q) || item.name.toLowerCase().includes(q);
  });
}
